# Generated by Django 5.1.2 on 2024-10-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='arrival_status',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timeout_status',
            field=models.CharField(blank=True, choices=[('ontime', 'On Time'), ('early', 'Left Early'), ('overtime', 'Overtime')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='defaultuser', max_length=100, unique=True),
        ),
    ]
