# Generated by Django 5.1.2 on 2024-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('timeout', models.TimeField()),
                ('reason', models.TextField(blank=True)),
            ],
        ),
    ]
