# Generated by Django 5.1.2 on 2024-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customtimeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomTimeout',
        ),
    ]
