# Generated by Django 5.1.2 on 2024-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attendance_time_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_duration_hours', models.FloatField(default=3)),
            ],
        ),
    ]
