# Generated by Django 5.1.2 on 2024-12-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_defaultschedule_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimesetting',
            name='overtime_duration_hours',
            field=models.IntegerField(default=3),
        ),
    ]
